steps:

- id: "Rodando Testes"
  name: 'gcr.io/cloud-builders/go'
  args: ['test', './src/', '-v']

- id: "Criando Imagem"
  name: "gcr.io/cloud-builders/docker"
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/goapp:latest'
  - '.'
images:
- 'gcr.io/$PROJECT_ID/goapp:latest'